Pcra Dsuite notes

1. use Pcra and Gmac bam files of reads mapped to O. orca reference genome (from Delphinidae phylogenomics analysis)

# Generate VCF files and merge them together:
sbatch Pcra_bam2vcf_Sedna.sh
Submitted batch job 2333693 (6/11/25)

# 1. merge vcf
sbatch VCFmerge_norm_filter_Sedna.sh
Submitted batch job 2339491, 6/12/25
#output = Ziphiid_filtered.vcf.gz, 75.6 GB.

#  split a multi-chromosome VCF file into separate files and run them in parallel.
# This script will take a VCF file containing data from all chromosomes and splits it into separate files per-chromosome. The output will go to a new folder that is passed to the script in Step 2.

sbatch 1.split_vcf_by_chrom.sh
Submitted batch job 2348665, 6/16/25

# Delete non-chromosome scaffold VCF files.
# rename sample names in all VCF files (and index files?) to sp_ID format (to match tree)
sbatch VCF_rename_samples.sh
Submitted batch job 2352582, 6/16/25

## Step 2: Create DTrios jobs and submit as SLURM job array

# This script takes the folder from Step 1 containing the per-chromosome (or single chromosome, or whole genome if you want) and create a SLURM job array that runs DTrios on each file.
# NOTE: The script by default automatically submits the SLURM job script. Disable this by commenting out the last line of the script "2.DTrios.sh" (sbatch "$JOB_SCRIPT").

sbatch 2.DTrios_setup.sh
Submitted batch job 2354047, 6/16/25

## Step 3: Combine DTrios output with Dtrioscombine (OPTIONAL!)
# This step will take the "_combine.txt" files from the individual Dtrios runs and combine them into a single result file.
# NOTE: _If you only run a single VCF file through the DTrios step, then you can skip this and move on to Step 4!
 sbatch 3.Dtrioscombine-v2.sh
Submitted batch job 2355530, 6/17/25

## Step 4: Generate D, _f_-4 ratio figures
#This step will generate figures of the D-statistic and _f_-4 ratio. These plots are good to get an overall view of the total signal observed in the data.
sbatch 4.figures.sh
# ran commands manually rather than in batch script.

## Step 5: Generate _f_-branch values and figure
# This last step will generate your _f_-branch statistics and then generate a figure of the results. This is the data I would recommend looking at when evaluating introgression.

5.f-branch (ran commands manually. )

## Optional Figure - Venn Diagram
(not done)
# I also provided the R script (Dsuite_vendiagram.R) for plotting a Venn diagram of the different D-statistic values generated by DTrios/Dtrioscombine. It provides you an insight into how the different ways of evaluating D compare.
# You can read more about how to interpret the Venn diagram on the tutorial page.


##########################################################
## Generated phylogeny for samples used in Trios.
# sbatch Pcra_Consensus_genome_woIUPAC_Angsd_Sedna.sh
Submitted batch job 2348913, 6/16/25

# extract Busco loci and generate consensus phylogeny for Dsuite.
sbatch Pcra_extract_genes_200-15kb_array_Sedna.sh
Submitted batch job 2352837, 6/16/25

# generate alignments for BUSCO loci
sbatch Pcra_200-15kb_split_fasta_to_gene_alignments_Sedna.sh
Submitted batch job 2352948, 6/16/25
# 5285 loci

# filter out loci with >0.1% missing data (N's)
sbatch Remove_Busco_locus_files_with_1pctN_Sedna.sh
Submitted batch job 2353049, 6/16/25
high Ns = 1540 loci
low Ns = 3744 loci

# IQTree phylogeny
# imported all 3744 loci into Geneious to concatenate, but concatenated file of all loci is too big for online version of IQtree (max 20MB, uncompressed fasta). 
# larges loci (locus number ≥ 5000): 129 loci, total length = 1,847,386bp. 
# Tree file = Pcra_Gmac_Oorc_129_largest_Busco.newick. Rearranged and bootstrap support removed for Dsuite: Pcra_Gmac_Oorc_129_largest_Busco_rearranged.newick


